CREATE TABLE $tableName (
  `id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `inner_client_id` tinyint(3) unsigned DEFAULT NULL,
  `name` varchar(50) NOT NULL,
  `login` varchar(50) NOT NULL,
  `password` varchar(100) DEFAULT NULL,
  `document_link` varchar(150) DEFAULT NULL,
  `status_id` tinyint(3) unsigned DEFAULT NULL,
  `link` varchar(255) DEFAULT NULL,
  `tool_id` smallint(5) unsigned DEFAULT NULL,
  `note` varchar(2000) DEFAULT NULL,
  `owner_id` smallint(5) unsigned NOT NULL,
  `created_by` smallint(5) unsigned DEFAULT NULL,
  `entity_id` tinyint(3) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `accounts_inner_client_id_foreign` (`inner_client_id`),
  KEY `accounts_status_id_foreign` (`status_id`),
  KEY `accounts_tool_id_foreign` (`tool_id`),
  KEY `accounts_owner_id_foreign` (`owner_id`),
  KEY `accounts_created_by_foreign` (`created_by`),
  KEY `accounts_entity_id_foreign` (`entity_id`),
  CONSTRAINT `accounts_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `accounts_entity_id_foreign` FOREIGN KEY (`entity_id`) REFERENCES `entities` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `accounts_inner_client_id_foreign` FOREIGN KEY (`inner_client_id`) REFERENCES `inner_clients` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `accounts_owner_id_foreign` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `accounts_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `accounts_tool_id_foreign` FOREIGN KEY (`tool_id`) REFERENCES `tools` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
)
