CREATE TABLE $tableName (
  `id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `action_id` bigint(20) unsigned DEFAULT NULL,
  `object_id` bigint(20) unsigned DEFAULT NULL,
  `tool_id` smallint(5) unsigned DEFAULT NULL,
  `is_draft` tinyint(1) NOT NULL DEFAULT 0,
  `entity_id` tinyint(3) unsigned DEFAULT NULL,
  `placement_id` mediumint(8) unsigned DEFAULT NULL,
  `created_by` smallint(5) unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `checklist_items_entity_id_foreign` (`entity_id`),
  KEY `checklist_items_created_by_foreign` (`created_by`),
  KEY `checklist_items_placement_id_foreign` (`placement_id`),
  KEY `checklist_items_action_id_foreign` (`action_id`),
  KEY `checklist_items_object_id_foreign` (`object_id`),
  KEY `checklist_items_tool_id_foreign` (`tool_id`),
  CONSTRAINT `checklist_items_action_id_foreign` FOREIGN KEY (`action_id`) REFERENCES `actions` (`id`) ON DELETE SET NULL,
  CONSTRAINT `checklist_items_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `checklist_items_entity_id_foreign` FOREIGN KEY (`entity_id`) REFERENCES `entities` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `checklist_items_object_id_foreign` FOREIGN KEY (`object_id`) REFERENCES `objects` (`id`) ON DELETE SET NULL,
  CONSTRAINT `checklist_items_placement_id_foreign` FOREIGN KEY (`placement_id`) REFERENCES `placements` (`id`) ON DELETE SET NULL,
  CONSTRAINT `checklist_items_tool_id_foreign` FOREIGN KEY (`tool_id`) REFERENCES `tools` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
)
