CREATE TABLE $tableName (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `edit_id` mediumint(8) unsigned DEFAULT NULL,
  `progressable_type` varchar(255) DEFAULT NULL,
  `progressable_id` bigint(20) unsigned DEFAULT NULL,
  `entity_block_id` smallint(5) unsigned DEFAULT NULL,
  `type` enum('edit','suggestion') NOT NULL DEFAULT 'edit',
  `status_id` tinyint(3) unsigned DEFAULT NULL,
  `done` tinyint(1) NOT NULL DEFAULT 0,
  `completed_by` smallint(5) unsigned DEFAULT NULL,
  `completed_at` timestamp NULL DEFAULT NULL,
  `created_by` smallint(5) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `edits_progress_edit_id_foreign` (`edit_id`),
  KEY `edits_progress_progressable_type_progressable_id_index` (`progressable_type`,`progressable_id`),
  KEY `edits_progress_status_id_foreign` (`status_id`),
  KEY `edits_progress_created_by_foreign` (`created_by`),
  KEY `edits_progress_entity_block_id_foreign` (`entity_block_id`),
  KEY `edits_progress_completed_by_foreign` (`completed_by`),
  CONSTRAINT `edits_progress_completed_by_foreign` FOREIGN KEY (`completed_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `edits_progress_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `edits_progress_edit_id_foreign` FOREIGN KEY (`edit_id`) REFERENCES `edits` (`id`) ON DELETE SET NULL,
  CONSTRAINT `edits_progress_entity_block_id_foreign` FOREIGN KEY (`entity_block_id`) REFERENCES `entity_block` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `edits_progress_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
)
