CREATE TABLE $tableName (
  `id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `entity_id` tinyint(3) unsigned DEFAULT NULL,
  `inner_client_id` tinyint(3) unsigned DEFAULT NULL,
  `quantity` tinyint(3) unsigned NOT NULL,
  `status_id` tinyint(3) unsigned DEFAULT NULL,
  `profession_id` bigint(20) unsigned DEFAULT NULL,
  `manager_id` smallint(5) unsigned DEFAULT NULL,
  `rate_id` tinyint(3) unsigned DEFAULT NULL,
  `shift_id` tinyint(3) unsigned DEFAULT NULL,
  `created_by` smallint(5) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `close_date` date DEFAULT NULL,
  `demand_date` date DEFAULT NULL,
  `sum_job_applications` smallint(5) unsigned NOT NULL DEFAULT 0,
  `note` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `job_requests_entity_id_foreign` (`entity_id`),
  KEY `job_requests_inner_client_id_foreign` (`inner_client_id`),
  KEY `job_requests_status_id_foreign` (`status_id`),
  KEY `job_requests_profession_id_foreign` (`profession_id`),
  KEY `job_requests_manager_id_foreign` (`manager_id`),
  KEY `job_requests_rate_id_foreign` (`rate_id`),
  KEY `job_requests_shift_id_foreign` (`shift_id`),
  KEY `job_requests_created_by_foreign` (`created_by`),
  CONSTRAINT `job_requests_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `job_requests_entity_id_foreign` FOREIGN KEY (`entity_id`) REFERENCES `entities` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `job_requests_inner_client_id_foreign` FOREIGN KEY (`inner_client_id`) REFERENCES `inner_clients` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `job_requests_manager_id_foreign` FOREIGN KEY (`manager_id`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `job_requests_profession_id_foreign` FOREIGN KEY (`profession_id`) REFERENCES `professions` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `job_requests_rate_id_foreign` FOREIGN KEY (`rate_id`) REFERENCES `rates` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `job_requests_shift_id_foreign` FOREIGN KEY (`shift_id`) REFERENCES `shifts` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `job_requests_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`) ON DELETE SET NULL
)
