CREATE TABLE $tableName (
  `id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `entity_id` tinyint(3) unsigned DEFAULT NULL,
  `status_id` tinyint(3) unsigned DEFAULT NULL,
  `title` varchar(150) DEFAULT NULL,
  `profession_id` bigint(20) unsigned DEFAULT NULL,
  `similar_profession_id` bigint(20) unsigned DEFAULT NULL,
  `role_overview` varchar(1500) DEFAULT NULL,
  `sum_jas` smallint(6) NOT NULL DEFAULT 0,
  `sum_job_posts` smallint(6) NOT NULL DEFAULT 0,
  `created_by` smallint(5) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `job_templates_entity_id_foreign` (`entity_id`),
  KEY `job_templates_status_id_foreign` (`status_id`),
  KEY `job_templates_created_by_foreign` (`created_by`),
  KEY `job_templates_profession_id_foreign` (`profession_id`),
  KEY `job_templates_similar_profession_id_foreign` (`similar_profession_id`),
  CONSTRAINT `job_templates_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `job_templates_entity_id_foreign` FOREIGN KEY (`entity_id`) REFERENCES `entities` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `job_templates_profession_id_foreign` FOREIGN KEY (`profession_id`) REFERENCES `professions` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `job_templates_similar_profession_id_foreign` FOREIGN KEY (`similar_profession_id`) REFERENCES `professions` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `job_templates_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
)
