CREATE TABLE $tableName (
  `id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `login` varchar(100) NOT NULL,
  `password` varchar(100) NOT NULL,
  `profile_link` varchar(255) NOT NULL,
  `note` varchar(500) DEFAULT NULL,
  `status_id` tinyint(3) unsigned DEFAULT NULL,
  `inner_client_id` tinyint(3) unsigned DEFAULT NULL,
  `job_site_id` smallint(5) unsigned DEFAULT NULL,
  `created_by` smallint(5) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `active_job_posts` tinyint(4) NOT NULL DEFAULT 0,
  `available_job_posts` tinyint(4) NOT NULL DEFAULT 0,
  `entity_id` tinyint(3) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `job_accounts_inner_client_id_foreign` (`inner_client_id`),
  KEY `job_accounts_job_site_id_foreign` (`job_site_id`),
  KEY `job_accounts_status_id_foreign` (`status_id`),
  KEY `job_accounts_created_by_foreign` (`created_by`),
  KEY `job_accounts_entity_id_foreign` (`entity_id`),
  CONSTRAINT `job_accounts_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `job_accounts_entity_id_foreign` FOREIGN KEY (`entity_id`) REFERENCES `entities` (`id`) ON DELETE SET NULL,
  CONSTRAINT `job_accounts_inner_client_id_foreign` FOREIGN KEY (`inner_client_id`) REFERENCES `inner_clients` (`id`) ON DELETE SET NULL,
  CONSTRAINT `job_accounts_job_site_id_foreign` FOREIGN KEY (`job_site_id`) REFERENCES `job_sites` (`id`) ON DELETE SET NULL,
  CONSTRAINT `job_accounts_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`) ON DELETE SET NULL
)
