CREATE TABLE $tableName (
  `id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `entity_id` tinyint(3) unsigned DEFAULT NULL,
  `job_account_id` smallint(5) unsigned DEFAULT NULL,
  `account_id` smallint(5) unsigned DEFAULT NULL,
  `slug` varchar(100) DEFAULT NULL,
  `published_site` tinyint(1) NOT NULL DEFAULT 0,
  `publish_date` datetime DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `full_post` varchar(4000) NOT NULL,
  `planned_date` date NOT NULL,
  `published_by` smallint(5) unsigned DEFAULT NULL,
  `status_id` tinyint(3) unsigned DEFAULT NULL,
  `link` varchar(255) DEFAULT NULL,
  `cost` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `currency_id` tinyint(3) unsigned DEFAULT NULL,
  `country_id` bigint(20) unsigned DEFAULT NULL,
  `city_id` bigint(20) unsigned DEFAULT NULL,
  `post_template_id` smallint(5) unsigned DEFAULT NULL,
  `sum_jas` smallint(5) unsigned NOT NULL DEFAULT 0,
  `shift_id` tinyint(3) unsigned DEFAULT NULL,
  `created_by` smallint(5) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `job_posts_entity_id_foreign` (`entity_id`),
  KEY `job_posts_job_account_id_foreign` (`job_account_id`),
  KEY `job_posts_account_id_foreign` (`account_id`),
  KEY `job_posts_published_by_foreign` (`published_by`),
  KEY `job_posts_status_id_foreign` (`status_id`),
  KEY `job_posts_currency_id_foreign` (`currency_id`),
  KEY `job_posts_country_id_foreign` (`country_id`),
  KEY `job_posts_city_id_foreign` (`city_id`),
  KEY `job_posts_created_by_foreign` (`created_by`),
  KEY `job_posts_shift_id_foreign` (`shift_id`),
  KEY `job_posts_post_template_id_foreign` (`post_template_id`),
  CONSTRAINT `job_posts_account_id_foreign` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `job_posts_city_id_foreign` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `job_posts_country_id_foreign` FOREIGN KEY (`country_id`) REFERENCES `countries` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `job_posts_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `job_posts_currency_id_foreign` FOREIGN KEY (`currency_id`) REFERENCES `currencies` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `job_posts_entity_id_foreign` FOREIGN KEY (`entity_id`) REFERENCES `entities` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `job_posts_job_account_id_foreign` FOREIGN KEY (`job_account_id`) REFERENCES `job_accounts` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `job_posts_post_template_id_foreign` FOREIGN KEY (`post_template_id`) REFERENCES `post_templates` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `job_posts_published_by_foreign` FOREIGN KEY (`published_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `job_posts_shift_id_foreign` FOREIGN KEY (`shift_id`) REFERENCES `shifts` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `job_posts_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
)
