CREATE TABLE $tableName (
  `id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `entity_id` tinyint(3) unsigned DEFAULT NULL,
  `name` varchar(300) NOT NULL,
  `url` text DEFAULT NULL,
  `tool_id` smallint(5) unsigned DEFAULT NULL,
  `inner_client_id` tinyint(3) unsigned DEFAULT NULL,
  `object_id` bigint(20) unsigned DEFAULT NULL,
  `description` varchar(2000) DEFAULT NULL,
  `owner_id` smallint(5) unsigned DEFAULT NULL,
  `status_id` tinyint(3) unsigned DEFAULT NULL,
  `format_id` smallint(5) unsigned DEFAULT NULL,
  `created_by` smallint(5) unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `links_entity_id_foreign` (`entity_id`),
  KEY `links_tool_id_foreign` (`tool_id`),
  KEY `links_inner_client_id_foreign` (`inner_client_id`),
  KEY `links_owner_id_foreign` (`owner_id`),
  KEY `links_status_id_foreign` (`status_id`),
  KEY `links_format_id_foreign` (`format_id`),
  KEY `links_created_by_foreign` (`created_by`),
  KEY `links_object_id_foreign` (`object_id`),
  CONSTRAINT `links_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `links_entity_id_foreign` FOREIGN KEY (`entity_id`) REFERENCES `entities` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `links_format_id_foreign` FOREIGN KEY (`format_id`) REFERENCES `formats` (`id`) ON DELETE CASCADE,
  CONSTRAINT `links_inner_client_id_foreign` FOREIGN KEY (`inner_client_id`) REFERENCES `inner_clients` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `links_object_id_foreign` FOREIGN KEY (`object_id`) REFERENCES `objects` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `links_owner_id_foreign` FOREIGN KEY (`owner_id`) REFERENCES `accounts` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `links_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `links_tool_id_foreign` FOREIGN KEY (`tool_id`) REFERENCES `tools` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
)
