CREATE TABLE $tableName (
  `id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `entity_id` tinyint(3) unsigned DEFAULT NULL,
  `title` varchar(250) NOT NULL,
  `job_template_id` smallint(5) unsigned DEFAULT NULL,
  `translation_id` bigint(20) unsigned DEFAULT NULL,
  `prompt` varchar(2000) DEFAULT NULL,
  `role_overview` varchar(1500) DEFAULT NULL,
  `full_post_template` varchar(8000) NOT NULL,
  `destination` enum('account','job_account') DEFAULT NULL,
  `status_id` tinyint(3) unsigned DEFAULT NULL,
  `created_by` smallint(5) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `post_templates_entity_id_foreign` (`entity_id`),
  KEY `post_templates_job_template_id_foreign` (`job_template_id`),
  KEY `post_templates_status_id_foreign` (`status_id`),
  KEY `post_templates_created_by_foreign` (`created_by`),
  KEY `post_templates_translation_id_foreign` (`translation_id`),
  CONSTRAINT `post_templates_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `post_templates_entity_id_foreign` FOREIGN KEY (`entity_id`) REFERENCES `entities` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `post_templates_job_template_id_foreign` FOREIGN KEY (`job_template_id`) REFERENCES `job_templates` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `post_templates_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `post_templates_translation_id_foreign` FOREIGN KEY (`translation_id`) REFERENCES `languages` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
)
