CREATE TABLE $tableName (
  `id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `person_id` smallint(5) unsigned DEFAULT NULL,
  `contract_url` varchar(1500) DEFAULT NULL,
  `entity_id` tinyint(3) unsigned DEFAULT NULL,
  `inner_client_id` tinyint(3) unsigned DEFAULT NULL,
  `shift_id` tinyint(3) unsigned DEFAULT NULL,
  `status_id` tinyint(3) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `created_by` smallint(5) unsigned DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `talents_person_id_foreign` (`person_id`),
  KEY `talents_entity_id_foreign` (`entity_id`),
  KEY `talents_inner_client_id_foreign` (`inner_client_id`),
  KEY `talents_shift_id_foreign` (`shift_id`),
  KEY `talents_status_id_foreign` (`status_id`),
  KEY `talents_created_by_foreign` (`created_by`),
  CONSTRAINT `talents_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `talents_entity_id_foreign` FOREIGN KEY (`entity_id`) REFERENCES `entities` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `talents_inner_client_id_foreign` FOREIGN KEY (`inner_client_id`) REFERENCES `inner_clients` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `talents_person_id_foreign` FOREIGN KEY (`person_id`) REFERENCES `persons` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `talents_shift_id_foreign` FOREIGN KEY (`shift_id`) REFERENCES `shifts` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `talents_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
)
