CREATE TABLE $tableName (
  `id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `action_id` bigint(20) unsigned DEFAULT NULL,
  `object_id` bigint(20) unsigned DEFAULT NULL,
  `is_draft` tinyint(1) NOT NULL DEFAULT 0,
  `description` varchar(500) DEFAULT NULL,
  `cost` smallint(6) NOT NULL DEFAULT 0,
  `frequency_id` tinyint(3) unsigned DEFAULT NULL,
  `entity_id` tinyint(3) unsigned DEFAULT NULL,
  `task_quantity` smallint(6) NOT NULL DEFAULT 0,
  `expected_hours` time NOT NULL DEFAULT '00:00:00',
  `created_by` smallint(5) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `task_templates_frequency_id_foreign` (`frequency_id`),
  KEY `task_templates_entity_id_foreign` (`entity_id`),
  KEY `task_templates_created_by_foreign` (`created_by`),
  KEY `task_templates_action_id_foreign` (`action_id`),
  KEY `task_templates_object_id_foreign` (`object_id`),
  CONSTRAINT `task_templates_action_id_foreign` FOREIGN KEY (`action_id`) REFERENCES `actions` (`id`) ON DELETE SET NULL,
  CONSTRAINT `task_templates_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `task_templates_entity_id_foreign` FOREIGN KEY (`entity_id`) REFERENCES `entities` (`id`) ON DELETE CASCADE,
  CONSTRAINT `task_templates_frequency_id_foreign` FOREIGN KEY (`frequency_id`) REFERENCES `frequencies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `task_templates_object_id_foreign` FOREIGN KEY (`object_id`) REFERENCES `objects` (`id`) ON DELETE SET NULL
)
