CREATE TABLE $tableName (
  `id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `entity_id` tinyint(3) unsigned DEFAULT NULL,
  `order` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `task_queue` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `title` varchar(100) NOT NULL,
  `task_template_id` smallint(5) unsigned DEFAULT NULL,
  `status_id` tinyint(3) unsigned DEFAULT NULL,
  `milestone_id` bigint(20) unsigned DEFAULT NULL,
  `project_id` smallint(5) unsigned DEFAULT NULL,
  `start_date` datetime DEFAULT NULL,
  `due_date` datetime DEFAULT NULL,
  `priority_id` tinyint(3) unsigned DEFAULT NULL,
  `total_time` time DEFAULT '00:00:00',
  `is_completed` tinyint(1) NOT NULL DEFAULT 0,
  `created_by` smallint(5) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `note` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tasks_entity_id_foreign` (`entity_id`),
  KEY `tasks_task_template_id_foreign` (`task_template_id`),
  KEY `tasks_created_by_foreign` (`created_by`),
  KEY `tasks_status_id_foreign` (`status_id`),
  KEY `tasks_priority_id_foreign` (`priority_id`),
  KEY `tasks_milestone_id_foreign` (`milestone_id`),
  KEY `tasks_project_id_foreign` (`project_id`),
  CONSTRAINT `tasks_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `tasks_entity_id_foreign` FOREIGN KEY (`entity_id`) REFERENCES `entities` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `tasks_milestone_id_foreign` FOREIGN KEY (`milestone_id`) REFERENCES `milestones` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `tasks_priority_id_foreign` FOREIGN KEY (`priority_id`) REFERENCES `priorities` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `tasks_project_id_foreign` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `tasks_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `tasks_task_template_id_foreign` FOREIGN KEY (`task_template_id`) REFERENCES `task_templates` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
)
